apiVersion: platform.cost.io/v1alpha1
kind: PostgreSQL
metadata:
  name: postgres-demo
  namespace: default

spec:
  region: westeurope
  version: "16"
  sku: Standard_D4s_v3
  storageGB: 256
  backupRetentionDays: 14
  highAvailability: false
  environment: dev

  compositionSelector:
    matchLabels:
      provider: azure
      resource: postgres