from github_client import GitHubClient
from branch_manager import BranchManager
from yaml_editor import YamlEditor
from pr_manager import PRManager


class RecommendationService:

    def __init__(self):

        self.github = GitHubClient()
        self.pr_manager = PRManager(self.github)

    def apply(self, request):

        # Check whether an open PR already exists for this file
        existing = self.pr_manager.find_open_pr_by_file(
            request.file_path
        )

        # -------------------------------------------------------
        # Existing PR found
        # -------------------------------------------------------
        if existing:

            branch = existing["branch"]

            file = self.github.read_file(
                request.file_path,
                branch
            )

            updated_yaml = YamlEditor.update_field(
                file["content"],
                request.field,
                request.recommended_value
            )

            self.github.update_file(
                file_path=request.file_path,
                branch=branch,
                new_content=updated_yaml,
                commit_message=f"Update {request.field} recommendation"
            )

            return {
                "status": "updated_existing_pr",
                "branch": branch,
                "pull_request": {
                    "url": existing["pr"].html_url,
                    "number": existing["pr"].number
                }
}

        # -------------------------------------------------------
        # No PR exists
        # -------------------------------------------------------

        branch = BranchManager.generate_branch_name(
            request.resource_name,
            f"{request.current_value}-to-{request.recommended_value}"
        )

        self.github.create_branch(branch)

        file = self.github.read_file(
            request.file_path
        )

        updated_yaml = YamlEditor.update_field(
            file["content"],
            request.field,
            request.recommended_value
        )

        self.github.update_file(
            file_path=request.file_path,
            branch=branch,
            new_content=updated_yaml,
            commit_message=f"Optimize {request.resource_name}"
        )

        pr = self.pr_manager.create_pr(
            branch=branch,
            title=f"Optimize {request.resource_name}",
            body=f"""
## Cost Optimization

Resource : {request.resource_name}

Current : {request.current_value}

Recommended : {request.recommended_value}

Estimated Savings : {request.estimated_savings}

Generated by Anomalyzer.
""",
        )

        return {
            "status": "new_pr_created",
            "branch": branch,
            "pull_request": pr
        }